advanced_section/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.IndexView.as_view()),
    path("basic_app/", include('basic_app.urls', namespace="basic_app")),
]

advanced_section/advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = 'basic_app'

urlpatterns = [
    path("", views.SchoolListView.as_view(), name="list"),
    path("<int:pk>/", views.SchoolDetailView.as_view(), name="detail"),
]

advanced_section/advcbv/basic_app/models.py
from django.db import models

# Create your models here.
class School(models.Model):

    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Student(models.Model):

    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,
                               related_name='students',
                               on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advanced_section/advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from . import models


class IndexView(TemplateView):

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['injectme'] = "BASIC INJECTION!"
        return context


class SchoolListView(ListView):

    model = models.School


class SchoolDetailView(DetailView):

    context_object_name = "school_details"
    model = models.School
    template_name = 'basic_app/school_detail.html'

advanced_section/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Base</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="#"></a>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>


  </body>
</html>

advanced_section/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Name: {{school_details.name}}</p>
    <p>Principal: {{school_details.principal}}</p>
    <p>Location: {{school_details.location}}</p>

    <h3>Students:</h3>

    {% for student in school_details.students.all %}
      <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
  </div>

{% endblock %}

advanced_section/advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>List of all schools:</h1>
<ol>
  {% for school in school_list %}
  <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>

{% endblock %}

advanced_section/advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Base</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="#"></a>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>


  </body>
</html>

advanced_section/advcbv/templates/index.html
{% extends "base.html" %}

{% block body_block %}

  <div class="jumbotron">
    <h1>Home Page</h1>
  </div>

{% endblock %}